// Generated by LiveScript 1.2.0
window.WCIO = {};
window.WCIO.main = function(){
  var vc, inVc, roomID, ref$;
  vc = new VideoChat();
  inVc = false;
  vc.onmeeting = function(it){
    if (!inVc && it.roomid === "webcamio-" + roomID) {
      inVc = true;
      vc.join(it.userid, it.roomID);
    }
  };
  vc.onaddstream = function(it){
    document.body.appendChild(it);
  };
  vc.onuserleft = function(it){
    var video;
    video = document.getElementById(it);
    video && video.parentNode.removeChild(video);
  };
  vc.sig.connect("http://amar.io:9980");
  roomID = (ref$ = window.location.href.match(/[^/]+$/g)) != null ? ref$[0] : void 8;
  if (!roomID) {
    roomID = 'xxxxxx'.replace(/[x]/g, function(){
      return (Math.random() * 36 | 0).toString(36);
    });
    console.log("Creating at " + roomID);
    inVc = true;
    vc.host("webcamio-" + roomID);
    return window.history.replaceState({}, "New Session ID", "/" + roomID);
  } else {
    console.log("Connecting to " + roomID);
    return window.setTimeout(function(){
      if (!inVc) {
        console.log("Creating at " + roomID);
        inVc = true;
        return vc.host("webcamio-" + roomID);
      }
    }, 3000);
  }
};