// Generated by LiveScript 1.2.0
window.WCIO = {};
window.WCIO.main = function(){
  var meeting, inMeeting, roomID, ref$;
  meeting = new Meeting;
  inMeeting = false;
  meeting.onmeeting = function(it){
    if (!inMeeting && it.roomid === "webcamio-" + roomID) {
      inMeeting = true;
      return meeting.meet(it);
    }
  };
  meeting.onaddstream = function(it){
    return document.body.appendChild(it.video);
  };
  meeting.onuserleft = function(it){
    var video;
    video = document.getElementById(it);
    return video && video.parentNode.removeChild(video);
  };
  meeting.openSignalingChannel = function(it){
    return io.connect("http://amar.io:9980").on('message', it);
  };
  roomID = (ref$ = window.location.href.match(/[^/]+$/g)) != null ? ref$[0] : void 8;
  if (!roomID) {
    roomID = 'xxxxxx'.replace(/[x]/g, function(){
      return (Math.random() * 36 | 0).toString(36);
    });
    console.log("Creating at " + roomID);
    inMeeting = true;
    meeting.setup("webcamio-" + roomID);
    return window.history.replaceState({}, "New Session ID", "/" + roomID);
  } else {
    console.log("Connecting to " + roomID);
    meeting.check("webcamio-" + roomID);
    return window.setTimeout(function(){
      if (!inMeeting) {
        console.log("Creating at " + roomID);
        inMeeting = true;
        return meeting.setup("webcamio-" + roomID);
      }
    }, 3000);
  }
};